# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GHImagePicker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   pod 'Masonry', '~> 1.1.0'

  # Pods for GHImagePicker

  target 'GHImagePickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GHImagePickerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
